# Use an official Maven image to build the project
FROM maven:3.8.4-openjdk-17 AS build

# Set the working directory in the container
WORKDIR /app

# Copy the entire project into the working directory
COPY . .

# Build the project with Maven (this assumes your Maven project uses a pom.xml file)
RUN mvn clean package

# Use a lightweight Tomcat image to deploy the WAR
FROM tomcat:10.1.31-jdk17

# Set the location of the WAR file generated by Maven
# (Assumes the WAR is in the /target directory after Maven build)
COPY --from=build /D/target/.war /usr/local/tomcat/webapps/app.war

# Expose the port where Tomcat runs
EXPOSE 8080

# Start Tomcat when the container starts
CMD ["catalina.sh", "run"]
